### ISSUE TITLE
M1 chip support

### ISSUE THREAD

**Issue by Queens-Aerospace** [edouardrolland/vscode_ros2_px4_workspace#1] opened 2023-10-30 20:09 UTC
Hello, 

I've been using this template for my aerospace designs team and everyone with a mac M1 chip cannot get this to work. I am wondering if we this could be modified to work with Mac M1 chip, it would be incredibly helpful. Thanks.

**Comment by kasperg3** [comment] 2023-10-31 08:12
I think the change should be fairly simple. The core of the problem is that the base docker image (Ubuntu 22.04) is not compatible with the arm architecture of the M1 chipset. 

I will see if I can compile a new image specifically for m1 and get back to you.

I will most likely have it done this week.

**Comment by ConorSpace** [comment] 2023-11-07 21:27
Hello,

I am also running into the same issue have there been any updates.

**Comment by kasperg3** [comment] 2023-12-20 12:04
Hi, 

I believe this issue has been fixed by a change in a docker dependency (https://hub.docker.com/r/althack/ros2/tags?page=1&name=humble-full which now works for ARM/M1 chips). Let me know whether you can build the container, as I am not able to test whether the change is a fix. 

@ConorSpace @Queens-Aerospace

**Closed as completed** 2024-01-12 09:18 UTC
